###
GET http://localhost

###
GET http://localhost/api

###
GET http://localhost/api/health

###
GET http://localhost/test_frontend

###
POST http://localhost/api/auth/signUp
content-type: application/json

{
  "username": "string",
  "password": "string",
  "avatar": "string",
  "is_admin": true
}
