###
GET http://localhost

###
GET http://localhost/api

###
GET http://localhost/api/health

###
GET http://localhost/test_frontend

###
POST http://localhost/api/auth/signUp
content-type: application/json

{
  "username": "user1",
  "password": "Aa1234567",
  "avatar": "avatar.jpg",
  "is_admin": true
}
